from compatability_calc import *
from helper_functions import *

class user_file_generator:

    def __init__(self, u_prefs, u_scores):
        self.user_preferences = u_prefs
        self.user_scores = u_scores
        
    # Generates the User's info file
    # regarding which genre of movies
    # he/she would be most interested in
    #
    #
    # function: user_file_generate
    #
    # returns: u_pref      User preferences
    #          percentages User's percentages of genres liked
    #
    #
    # parameters: N/A
    #
    #
    # @author MonkaS
    # @since 3/11/2021

    def user_file_generate(self):

        with open("output_files/user_info.txt", "w", encoding='utf8') as file:
            file.write("Generated by The Movie Recommender\n")
            file.write("Developed by MonkaS\n")
            file.write("Copyright 2021\n\n\n")
            u_pref = sorted(self.user_preferences)
            u_pref = helper_functions().convert(u_pref)
            file.write("Genre List: " + u_pref + "\n\n\n")
            u_pref = u_pref.split(", ")

            file.write("Movie Genre Percent Matches\n\n")

        file.close()

        calc = compat_calc(self.user_preferences, self.user_scores, "output_files/user_info.txt")
        percentages = calc.calc_percents()

        file.close()

        return u_pref, percentages
