from question_engine import *

# Converts a list to a string
# with spaces between indices
#
#
# function: convert
#
# returns:
#          A string of the indices in the list with spaces
#          placed between each one
#
# parameters:
#          question_file [string] The input question text file
#
# @author MonkaS
# @since 3/11/2021

def convert(l):
    return ' '.join(l)


# Generates the User's info file
# regarding which genre of movies
# he/she would be most interested in
#
#
# function: user_file_generator
#
# returns: N/A
#
#
# parameters: question_file [string] The input text file containing the questions
#
#
# @author MonkaS
# @since 3/11/2021

def user_file_generator(questions_file):

    user_preferences, user_scores = question_engine(questions_file)
    score_total = sum(user_scores)
    percentages = []

    with open("output_files/user_info.txt", "w", encoding='utf8') as file:
        file.write("Generated by The Movie Recommender\n")
        file.write("Developed by MonkaS\n")
        file.write("Copyright 2021\n\n\n")
        u_pref = sorted(user_preferences)
        u_pref = convert(u_pref)
        file.write("Genre List: " + u_pref + "\n\n\n")
        u_pref = u_pref.split()

        file.write("Movie Genre Percent Matches\n\n")

        for pf in range(len(u_pref)):
            percentages.append(round((user_scores[user_preferences.index(u_pref[pf])]/score_total) * 100.0, 2))
            file.write(u_pref[pf] + ": " + str(round((user_scores[user_preferences.index(u_pref[pf])]/score_total) * 100.0, 2)) + "%\n")

        #file.write("\n\n\n\nYour Top 10 Movies You May Enjoy")


    file.close()
